-- Number of customers

SELECT COUNT(*) AS total_customers
FROM customers;

-- Number of products
SELECT COUNT(*) AS total_products
FROM products;

-- Number of orders
SELECT COUNT(*) AS total_orders
FROM orders;    

-- Number of order items
SELECT COUNT(*) AS total_order_items
FROM order_items;

-- What is the total revenue generated by completed orders?
SELECT
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS total_revenue
FROM orders o
    JOIN order_items oi 
        ON oi.order_id = o.order_id
WHERE o.status = 'Completed';

-- What is the average order value (AOV) for completed orders?
SELECT 
    ROUND(SUM(oi.quantity * oi.unit_price) / COUNT(DISTINCT o.order_id), 2) AS average_order_value
FROM orders o
    JOIN order_items oi
        ON oi.order_id = o.order_id
WHERE o.status = 'Completed';

-- How much revenue does each country generate?
SELECT c.country,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS revenue
FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    JOIN order_items oi ON o.order_id = oi.order_id
WHERE o.status = 'Completed'
GROUP BY c.country
ORDER BY revenue DESC;

-- Who are the top 10 customers by revenue?
SELECT
    c.customer_id,
    C.customer_name,
    round(SUM(oi.quantity * oi.unit_price), 2) AS total_revenue,
    RANK() OVER (ORDER BY SUM(oi.quantity * oi.unit_price) DESC) AS revenue_rank
FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    JOIN order_items oi ON o.order_id = oi.order_id
WHERE o.status = 'Completed'
GROUP BY c.customer_id, c.customer_name
ORDER BY revenue_rank
LIMIT 10;

-- Which products generate the most revenue?
SELECT
    p.product_id,
    p.product_name,
    p.category,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS total_revenue,
    DENSE_RANK() OVER (ORDER BY SUM(oi.quantity * oi.unit_price) DESC) AS revenue_dense_rank
FROM products p
    JOIN order_items oi ON p.product_id = oi.product_id
    JOIN orders o ON oi.order_id = o.order_id
WHERE o.status = 'Completed'
GROUP BY p.product_id, p.product_name, p.category
ORDER BY revenue_dense_rank
LIMIT 10;

-- How does revenue change month over month?
SELECT
    TO_CHAR(o.order_date, 'YYYY-MM') AS order_month,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS monthly_revenue
FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
WHERE o.status = 'Completed'
GROUP BY TO_CHAR(o.order_date, 'YYYY-MM')
ORDER BY order_month;

-- How much did revenue grow or decrease compared with the previous month?

WITH monthly_revenue AS (
    SELECT
        TO_CHAR(o.order_date, 'YYYY-MM') AS order_month,
        ROUND(SUM(oi.quantity * oi.unit_price), 2) AS monthly_revenue
    FROM orders o
        JOIN order_items oi ON o.order_id = oi.order_id
    WHERE o.status = 'Completed'
    GROUP BY TO_CHAR(o.order_date, 'YYYY-MM')
),
monthly_revenue_with_lag AS (SELECT
    order_month,
    monthly_revenue,
    LAG(monthly_revenue) OVER (ORDER BY order_month) AS previous_month_revenue
FROM monthly_revenue
)
SELECT 
    order_month,
    monthly_revenue,
    previous_month_revenue,
    ROUND(monthly_revenue - previous_month_revenue, 2) AS revenue_change,
    TO_CHAR(CASE 
        WHEN previous_month_revenue IS NULL THEN NULL
        ELSE (monthly_revenue - previous_month_revenue) / previous_month_revenue * 100
    END, 'FM999999990.00%') AS revenue_change_percentage
FROM monthly_revenue_with_lag
ORDER BY order_month;

-- Which customers are returning customers?

SELECT c.customer_id,
    c.customer_name,
    COUNT(DISTINCT o.order_id) AS total_orders
FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
WHERE o.status = 'Completed'
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(DISTINCT o.order_id) >= 2
ORDER BY total_orders DESC;

-- What percentage of customers are returning customers?

WITH customer_order AS (
    SELECT c.customer_id,
           c.customer_name,
        COUNT(DISTINCT o.order_id) AS total_orders
    FROM customers c
        JOIN orders o ON c.customer_id = o.customer_id
    WHERE o.status = 'Completed'
    GROUP BY c.customer_id, c.customer_name
),
customer_type AS (
    SELECT 
        customer_id,
        CASE
            WHEN total_orders >= 2 THEN 'Returning'
            ELSE 'One-time'
        END AS customer_type

    FROM customer_order
)
SELECT 
    customer_type,
    COUNT(*) * 100.0 / SUM(COUNT(*)) OVER() AS percentage_of_customers
FROM customer_type
GROUP BY customer_type
ORDER BY percentage_of_customers DESC;

-- How many customers made 1, 2, 3, 4+ completed orders?

WITH customer_orders AS (
    SELECT 
        c.customer_id,
        COUNT(DISTINCT o.order_id) AS total_orders
    FROM orders o
        JOIN customers c ON c.customer_id = o.customer_id
    WHERE o.status = 'Completed'
    GROUP BY c.customer_id
),
order_frequency AS (
    SELECT 
        customer_id,
        CASE 
            WHEN total_orders = 1 THEN '1 order'
            WHEN total_orders = 2 THEN '2 orders'
            WHEN total_orders = 3 THEN '3 orders'
            ELSE '4+ orders'
        END AS frequency
    FROM customer_orders
)
SELECT 
    frequency,
    COUNT (*) AS customer_count
FROM order_frequency
GROUP BY frequency
ORDER BY CASE frequency
        WHEN '1 order' THEN 1
        WHEN '2 orders' THEN 2
        WHEN '3 orders' THEN 3
        ELSE 4
    END;

-- Which product categories generate the most revenue?

SELECT 
    p.category,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS revenue
FROM products p
    JOIN order_items oi ON p.product_id = oi.product_id
    JOIN orders o ON o.order_id = oi.order_id
WHERE o.status = 'Completed'
GROUP BY p.category
ORDER BY revenue DESC;

-- What percentage of total revenue comes from each product category?

WITH category_revenue AS (
    SELECT 
    p.category,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS revenue
FROM products p
    JOIN order_items oi ON p.product_id = oi.product_id
    JOIN orders o ON o.order_id = oi.order_id
WHERE o.status = 'Completed'
GROUP BY p.category
)
SELECT
    category,
    revenue,
    ROUND(revenue / SUM(revenue) OVER () * 100.0, 2) AS percentage_category
FROM category_revenue cr
ORDER BY percentage_category DESC;

-- What is the top-selling product in each category?

WITH product_revenue AS (
    SELECT
        p.category,
        p.product_name,
        ROUND(SUM(oi.quantity * oi.unit_price), 2) AS revenue
    FROM products p
        JOIN order_items oi ON p.product_id = oi.product_id
        JOIN orders o ON oi.order_id = o.order_id
    WHERE o.status = 'Completed'
    GROUP BY p.category, p.product_name
),
ranked_products AS (
    SELECT 
        category,
        product_name,
        revenue,
        RANK() OVER (
            PARTITION BY category
            ORDER BY revenue DESC
        ) AS product_rank
    FROM product_revenue
)
SELECT 
    category,
    product_name,
    revenue,
    product_rank
FROM ranked_products
WHERE product_rank = 1
ORDER BY category;

-- What is the top-selling product in each category?

